server:
  port: 9000
spring:
  application:
    name: zuul
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
    register-with-eureka: true
    #是否需要从eureka上获取注册信息
    fetch-registry: true
    #表示eureka client间隔多久去拉取服务器注册信息,默认为30秒
    registry-fetch-interval-seconds: 10
  ##心跳检测与续约时间（测试环境和本地开发环境将值设置小一点，保证服务关闭后，注册中心能够及时踢出）
  instance:
    #客户端向Eureka注册中心发送心跳的时间间隔，单位为秒（默认为30s）,（客户端会按照此规则向Eureka服务端发送心跳检测包）
    lease-renewal-interval-in-seconds: 2
    #Eureka注册中心在收到客户端最后一次心跳之后等待的时间上限，单位为秒（默认为90s），超过时间则剔除（客户端会按照此规则向Eureka服务端发送心跳检测包）
    lease-expiration-duration-in-seconds: 2
zuul:
  routes:
    #定义Zuul网关转发的服务规则api-a和api-b等(这个规则名可以随便取)
    api-a:
      #以/api-custom/ 的访问请求, URL: 127.0.0.1:9999/api-custom/ ,会转发到feign-client
      path: /api-custom/**
      # 指定服务别名，表示需要转发到哪个服务
      serviceId: api-feign
