### 用户服务
server:
  port: 8101
###服务别名----服务注册到注册中心名称
spring:
  application:
    name: api-user
eureka:
  client:
    service-url:
      ##### 当前会员服务注册到eureka服务地址
      defaultZone: http://127.0.0.1:8000/eureka
    ### 需要将我的服务注册到eureka上
    register-with-eureka: true
    ####需要检索服务
    fetch-registry: true
  ##心跳检测与续约时间（测试环境和本地开发环境将值设置小一点，保证服务关闭后，注册中心能够及时踢出）
  instance:
    #客户端向Eureka注册中心发送心跳的时间间隔，单位为秒（默认为30s）,（客户端会按照此规则向Eureka服务端发送心跳检测包）
#    lease-renewal-interval-in-seconds: 22
    #Eureka注册中心在收到客户端最后一次心跳之后等待的时间上限，单位为秒（默认为90s），超过时间则剔除（客户端会按照此规则向Eureka服务端发送心跳检测包）
#    lease-expiration-duration-in-seconds: 22