###服务别名----服务注册到注册中心名称
spring:
  application:
    name: service-order
  cloud:
    config:
      name: ${spring.application.name}
      profile: dev   #profile对应config server所获取的配置文件中的{profile}
      label: master  #指定Git仓库的分支，对应config server所获取的配置文件的{label}
      discovery:
        #标记以指示启用配置服务器发现（配置服务器URL将通过发现查找）
        enabled: true
        #读取config-server注册地址
        service-id: config-server
      #uri: http://127.0.0.1:8080/
eureka:
  client:
    service-url:
      ##### 当前会员服务注册到eureka服务地址
      defaultZone: http://127.0.0.1:8000/eureka
    ### 需要将我的服务注册到eureka上
    register-with-eureka: true
    ####需要检索服务
    fetch-registry: true
  ##心跳检测与续约时间（测试环境和本地开发环境将值设置小一点，保证服务关闭后，注册中心能够及时踢出）
  instance:
    #客户端向Eureka注册中心发送心跳的时间间隔，单位为秒（默认为30s）,（客户端会按照此规则向Eureka服务端发送心跳检测包）
#    lease-renewal-interval-in-seconds: 2
    #Eureka注册中心在收到客户端最后一次心跳之后等待的时间上限，单位为秒（默认为90s），超过时间则剔除（客户端会按照此规则向Eureka服务端发送心跳检测包）
#    lease-expiration-duration-in-seconds: 2